# Generated by Django 4.2.7 on 2023-12-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historicalperformence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPerformence',
        ),
    ]
