# Generated by Django 4.2.7 on 2023-12-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_historical_performence'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_performence',
            name='quality_rating_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historical_performence',
            name='avarage_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historical_performence',
            name='fullfillment_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historical_performence',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0),
        ),
    ]
