# Generated by Django 4.2.7 on 2023-12-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_avarage_response_time_historical_performence_average_response_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historical_performence',
            old_name='fullfillment_rate',
            new_name='fulfillment_rate',
        ),
    ]
