# Generated by Django 4.2.7 on 2023-12-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_fullfillment_rate_historical_performence_fulfillment_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='api.vendor')),
            ],
        ),
    ]
